services:
  - type: web
    name: todo-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8080
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///todo.db
      - key: JWT_SECRET_KEY
        value: dev-secret-key-not-for-production-use
      - key: PRODUCTION_URL
        value: https://chankxow.github.io/01204223-flask-react-todo-68
