"""Add User table

Revision ID: 87891c14e940
Revises: c06d1525b123
Create Date: 2026-02-20 14:52:49.962873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87891c14e940'
down_revision = 'c06d1525b123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
